"""empty message

Revision ID: 22027cefeb97
Revises: bdbcc508f11a
Create Date: 2025-09-30 23:43:42.584009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22027cefeb97'
down_revision = 'bdbcc508f11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
